"""
golden_labels.py

The output of manually reading all 200 sampled customer messages (with their
real historical agent reply shown as context) and assigning:
  - true_intent: corrected against docs/intent_taxonomy.md (often differs
    from the cheap weak_intent regex label -- that's the point of hand
    labeling)
  - escalate: whether this message should be auto-handled or escalated,
    per the policy documented in docs/golden_set_methodology.md:
        escalate=True if resolving it requires account-specific data
        (DM'd email/username, payment lookup, security incident) or the
        real agent skipped generic troubleshooting and went straight to
        a DM/ticket. escalate=False if it's informational, feedback,
        acknowledgement, or answerable with generic self-serve steps.

Index i here corresponds to row i of data/golden/golden_sample_raw.csv
(after the fixed random seed sampling -- do not re-run the sampling script
after labeling, or the mapping breaks. This is why the raw sample is
checked into the repo instead of regenerated at eval time).
"""

# (true_intent, escalate)
LABELS = [

    ("feature_request_feedback", False),
    ("downloads_offline_issue", False),
    ("content_missing_restricted", False),
    ("general_chitchat_ack", False),
    ("content_missing_restricted", True),
    ("general_chitchat_ack", False),
    ("device_platform_support", False),
    ("billing_payment_subscription", True),
    ("playback_streaming_issue", False),
    ("login_account_access", True),
    ("general_chitchat_ack", False),
    ("playback_streaming_issue", False),
    ("playback_streaming_issue", False),
    ("login_account_access", True),
    ("downloads_offline_issue", False),
    ("family_plan_management", True),
    ("login_account_access", True),
    ("content_missing_restricted", True),
    ("feature_request_feedback", False),
    ("feature_request_feedback", False),
    ("feature_request_feedback", False),
    ("login_account_access", True),
    ("content_missing_restricted", False),
    ("playback_streaming_issue", False),
    ("playback_streaming_issue", False),
    ("general_chitchat_ack", False),
    ("content_missing_restricted", False),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("billing_payment_subscription", True),
    ("content_missing_restricted", True),
    ("billing_payment_subscription", True),
    ("general_chitchat_ack", False),
    ("billing_payment_subscription", True),
    ("billing_payment_subscription", True),
    ("downloads_offline_issue", False),
    ("feature_request_feedback", False),
    ("login_account_access", True),
    ("login_account_access", True),
    ("feature_request_feedback", False),
    ("downloads_offline_issue", False),
    ("downloads_offline_issue", False),
    ("general_chitchat_ack", False),
    ("billing_payment_subscription", True),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", True),
    ("family_plan_management", False),
    ("feature_request_feedback", False),
    ("login_account_access", True),
    ("billing_payment_subscription", True),
    ("device_platform_support", False),
    ("family_plan_management", True),
    ("family_plan_management", True),
    ("feature_request_feedback", False),
    ("login_account_access", True),
    ("feature_request_feedback", False),
    ("feature_request_feedback", False),
    ("downloads_offline_issue", False),
    ("feature_request_feedback", False),
    ("login_account_access", True),
    ("family_plan_management", True),
    ("login_account_access", True),
    ("login_account_access", True),
    ("content_missing_restricted", False),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("family_plan_management", True),
    ("downloads_offline_issue", False),
    ("feature_request_feedback", False),
    ("billing_payment_subscription", True),
    ("playback_streaming_issue", False),
    ("device_platform_support", False),
    ("downloads_offline_issue", False),
    ("feature_request_feedback", False),
    ("feature_request_feedback", False),
    ("family_plan_management", True),
    ("billing_payment_subscription", False),
    ("login_account_access", True),
    ("playback_streaming_issue", False),
    ("device_platform_support", False),
    ("playback_streaming_issue", False),
    ("playback_streaming_issue", False),
    ("playback_streaming_issue", False),
    ("family_plan_management", True),
    ("downloads_offline_issue", True),
    ("login_account_access", True),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("login_account_access", True),
    ("billing_payment_subscription", True),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("general_chitchat_ack", False),
    ("general_chitchat_ack", False),
    ("playback_streaming_issue", True),
    ("downloads_offline_issue", False),
    ("login_account_access", True),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", True),
    ("billing_payment_subscription", True),
    ("billing_payment_subscription", True),
    ("playback_streaming_issue", True),
    ("device_platform_support", False),
    ("feature_request_feedback", False),
    ("billing_payment_subscription", True),
    ("login_account_access", True),
    ("device_platform_support", False),
    ("general_chitchat_ack", False),
    ("billing_payment_subscription", True),
    ("family_plan_management", False),
    ("billing_payment_subscription", True),
    ("playback_streaming_issue", False),
    ("login_account_access", True),
    ("login_account_access", True),
    ("feature_request_feedback", False),
    ("feature_request_feedback", False),
    ("device_platform_support", False),
    ("general_chitchat_ack", False),
    ("content_missing_restricted", True),
    ("playback_streaming_issue", False),
    ("login_account_access", True),
    ("device_platform_support", False),
    ("general_chitchat_ack", False),
    ("feature_request_feedback", False),
    ("content_missing_restricted", False),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", False),
    ("general_chitchat_ack", False),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", True),
    ("device_platform_support", False),
    ("login_account_access", True),
    ("downloads_offline_issue", False),
    ("billing_payment_subscription", True),
    ("playback_streaming_issue", False),
    ("family_plan_management", True),
    ("content_missing_restricted", False),
    ("feature_request_feedback", False),
    ("general_chitchat_ack", False),
    ("playback_streaming_issue", False),
    ("device_platform_support", False),
    ("downloads_offline_issue", True),
    ("device_platform_support", False),
    ("login_account_access", True),
    ("billing_payment_subscription", True),
    ("content_missing_restricted", False),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", False),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", False),
    ("login_account_access", False),
    ("content_missing_restricted", False),
    ("playback_streaming_issue", True),
    ("billing_payment_subscription", True),
    ("content_missing_restricted", False),
    ("feature_request_feedback", False),
    ("content_missing_restricted", False),
    ("general_chitchat_ack", False),
    ("playback_streaming_issue", False),
    ("playback_streaming_issue", False),
    ("billing_payment_subscription", True),
    ("content_missing_restricted", False),
    ("feature_request_feedback", False),
    ("billing_payment_subscription", True),
    ("feature_request_feedback", False),
    ("general_chitchat_ack", False),
    ("billing_payment_subscription", True),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", False),
    ("feature_request_feedback", False),
    ("feature_request_feedback", False),
    ("billing_payment_subscription", True),
    ("general_chitchat_ack", False),
    ("device_platform_support", False),
    ("playback_streaming_issue", True),
    ("downloads_offline_issue", True),
    ("login_account_access", True),
    ("content_missing_restricted", False),
    ("content_missing_restricted", False),
    ("playback_streaming_issue", False),
    ("general_chitchat_ack", False),
    ("feature_request_feedback", False),
    ("playback_streaming_issue", False),
    ("downloads_offline_issue", False),
    ("playback_streaming_issue", False),
    ("general_chitchat_ack", False),
    ("playback_streaming_issue", False),
    ("general_chitchat_ack", False),
    ("login_account_access", True),
    ("content_missing_restricted", True),
    ("downloads_offline_issue", True),
    ("login_account_access", True),
    ("login_account_access", True),
    ("content_missing_restricted", True),
    ("billing_payment_subscription", True),
    ("login_account_access", True),
    ("content_missing_restricted", False),
    ("feature_request_feedback", False),
]

assert len(LABELS) == 200
